version: '3.3'
services:
  authentication:
    container_name: DEV-AUTHENTICATION
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    environment:
      - ENV=development
  hashicorp-vault:
    image: hashicorp/vault:1.17.5
    container_name: HASHICORP-VAULT
  hashicorp-consul:
    image: hashicorp/consul:1.17
    container_name: CONSUL-VAULT-STORAGE
    
