version: "3.3"
services:
  hashicorp-vault:
    image: hashicorp/vault:1.17.5
    container_name: HASHICORP-VAULT
    command: >
      sh -c "
        apk add --no-cache curl && \
        chmod +x /vault-init.sh && \
        vault server -dev -dev-root-token-id=root -dev-listen-address=0.0.0.0:8200 & \
        while ! curl --silent http://localhost:8200/v1/sys/health; do \
          echo 'Waiting for Vault to be ready...'; \
          sleep 2; \
        done && \
        echo 'Vault is ready!' && \
        /vault-init.sh && \
        tail -f /dev/null"

    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_ADDR: "http://0.0.0.0:8200"  # A conserver uniquement si vous êtes en mode DEV
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault-data:/vault/data  # Stockage persistant pour Vault
      - ./vault-init.sh:/vault-init.sh  # Stockage persistant pour Vault
    depends_on:
      - hashicorp-consul

  hashicorp-consul:
    image: hashicorp/consul:1.17
    container_name: CONSUL-VAULT-STORAGE
    ports:
      - "8500:8500"
    command: "agent -dev -client=0.0.0.0"
    volumes:
      - consul-data:/consul/data
volumes:
  consul-data:
  vault-data: 